### ISSUE TITLE
Origin of TF list for Homo sapiens

### ISSUE THREAD

**Issue by rebekabato** [pcahan1/CellNet#16]
Hi Patrick, 

I would like to ask where the TF list for Homo sapiens is from (data/hsTFs.rda)? Where did you retrieve this list of genes? 

I am comparing your list with the CisBP database, the number of Homo sapiens transcription factor genes is 1639 in that database. While the list that can be found in this tutorial (data/hsTFs.rda) contains 2139 genes. It would be tempting to use your TF list since that has more genes, but CisBP seems to be a more reliable source.

Thanks for the clarification!
Beka

**Comment by pcahan1** [comment]
Hi,

That list was generated based on combined GO annotation of "DNA-binding" and "regulation of transcription". It might be more accurate to call it a list of transcriptional regulators rather than a list of transcription factors. More recently we have decided to use a combination of the above automated strategy + our own curation + curated resources like the one you cite including:

http://bioinfo.life.hust.edu.cn/AnimalTFDB/#!/tf_summary?species=Homo_sapiens

https://tools.sschmeier.com/tcof/home/

HTH
