### ISSUE TITLE
interpreting NIS plot

### ISSUE THREAD

**Issue by avitalsteiman** [pcahan1/CellNet#23]
In the NIS plot, what does the colour range of the boxplot represent? P-value? 
Also what is the range of the NIS? In the RNA-seq paper (Radley et al. 2017) in figure 5a the range is much larger than in 5b, does that mean that the dysregulation in 5a is stronger than in 5b?
Thank you for your help.

**Comment by pcahan1** [comment]
Step 11-B in Radley et al 2017 has a call to plot_nis. This colors each box by NIS according to a multicolor gradient scaled from purple (low), white (zero), to orange (high). It is auto-scaled based on the input range so the depth of purple-ness, for example, is not comparable across plots. 

I have not defined the NIS range. The range will vary between GRNs because we did not adjust for network size (we should think about including this as an adjusted NIS output). However, I do agree with your statement "...dysregulation for Pou5f1 in 5a is much stronger than MYT1L in 5b". This is because 5A is calculated on fibroblast as a query/starting cell type, which is transcriptionally very distinct from the intended target of ESCs/PSCs. On the other hand, 5B is calculated based on iPSC-neuron as a starting cell type, which is transcriptionally closer to the intended target of a neuron.

**Comment by avitalsteiman** [comment]
Thank you for your helpful reply.
